SELECT *   
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	FULL JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID



SELECT SALES.CUSTOMER_ID, SUM(PRICE) AMOUNT_CUSTOMER_SPENT
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	GROUP BY SALES.CUSTOMER_ID
	
	SELECT SALES.CUSTOMER_ID,COUNT(ORDER_DATE) AS DAYS_VISITED
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	GROUP BY SALES.CUSTOMER_ID


SELECT SALES.CUSTOMER_ID,ORDER_DATE, PRODUCT_NAME
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	
	

SELECT DISTINCT(PRODUCT_NAME), COUNT(PRODUCT_NAME) AS PRODUCT_TIME
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	GROUP BY PRODUCT_NAME
	ORDER BY PRODUCT_TIME DESC


SELECT SALES.CUSTOMER_ID, PRODUCT_NAME, COUNT(PRODUCT_NAME) AS PRODUCT_TIME
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	GROUP BY SALES.CUSTOMER_ID, PRODUCT_NAME
	ORDER BY PRODUCT_TIME DESC

SELECT SALES.CUSTOMER_ID, PRODUCT_NAME, JOIN_DATE,ORDER_DATE
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	WHERE JOIN_DATE < ORDER_DATE
	ORDER BY SALES.CUSTOMER_ID



SELECT SALES.CUSTOMER_ID, PRODUCT_NAME, PRICE,JOIN_DATE,ORDER_DATE
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	WHERE JOIN_DATE > ORDER_DATE
	ORDER BY SALES.CUSTOMER_ID

SELECT SALES.CUSTOMER_ID, COUNT(PRODUCT_NAME) PRODUCT_COUNT, SUM(PRICE) SUM_PRICE
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	WHERE JOIN_DATE > ORDER_DATE
	GROUP BY SALES.CUSTOMER_ID


	      --USING CTE
WITH updatedprice (customer_id, product_id, product_name, price, NEWPRICE)
AS
(
SELECT sales.customer_id, sales.product_id, product_name, price,
            CASE 
	WHEN PRODUCT_NAME= 'SUSHI' THEN PRICE + (PRICE*10*2) 
    WHEN PRODUCT_NAME= 'CURRY' THEN PRICE +(PRICE*10) 
    WHEN PRODUCT_NAME= 'RAMEN' THEN PRICE + (PRICE*10)
END as NEWPRICE
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
)
SELECT *,
SUM(NEWPRICE) OVER(PARTITION BY CUSTOMER_ID) CALCULATEDNEWPRICE
FROM updatedprice
order by customer_id



       -- USING TEMPTABLE
DROP TABLE IF EXISTS #UPGRADEDPRICE
CREATE TABLE #UPGRADEDPRICE
(CUSTOMER_ID VARCHAR(255),
PRODUCT_ID INT,
PRODUCT_NAME VARCHAR(255),
PRICE INT,
LATESTPRICE INT,
)
INSERT INTO #UPGRADEDPRICE
SELECT sales.customer_id, sales.product_id, product_name, price,
            CASE 
	WHEN PRODUCT_NAME= 'SUSHI' THEN PRICE + (PRICE*10*2) 
    WHEN PRODUCT_NAME= 'CURRY' THEN PRICE +(PRICE*10) 
    WHEN PRODUCT_NAME= 'RAMEN' THEN PRICE + (PRICE*10)
END as LATESTPRICE
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID

SELECT *,
SUM(LATESTPRICE) OVER(PARTITION BY CUSTOMER_ID) CALCULATEDNEWPRICE
FROM #UPGRADEDPRICE
order by customer_id
	
	
SELECT SALES.CUSTOMER_ID, PRODUCT_NAME, JOIN_DATE,
SUM(PRICE*2) OVER(PARTITION BY SALES.CUSTOMER_ID)
FROM SALES
FULL JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	WHERE JOIN_DATE <= ORDER_DATE
	ORDER BY SALES.CUSTOMER_ID	
	


SELECT *   
FROM SALES
INNER JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
ORDER BY MENU.PRICE DESC

SELECT MEMBERS.CUSTOMER_ID, PRODUCT_NAME,PRICE
FROM SALES
INNER JOIN MEMBERS
	ON SALES.CUSTOMER_ID=MEMBERS.CUSTOMER_ID
	INNER JOIN MENU 
	ON SALES.PRODUCT_ID=MENU.PRODUCT_ID
	ORDER BY PRODUCT_NAME,PRICE
	